### ISSUE TITLE
Reg. Flashing Android Image on imx7-pico-pi

### ISSUE THREAD

**Issue by amsurana** [technexion-android/manifest#3]
Hi,

I download the repo https://github.com/technexion-android/manifest/tree/tn-o8.0.0_1.0.0-ga
and synced AOSP source code.

Can you please provide me right steps to flash the Android images on imx7 Pico PI board from TechNexion ? 

After building the code for PicoPI - userdebug using "Lunch" and "Make" command, I am unable to figure out how to flash the Images to eMMC ? 

Is there any documentation to:

1. Create a Prebuilt installer IMG file containing all the system.img, recovery.img, boot.img, cache.img, vendor.img, etc. I can then flash via Serial Mode. But there's not such documentation.
2. I flashed using *flashcard* program, but it seems I am stuck at a different issue below. 

Importing environment from mmc ...                                              
baseboard is pi                                                                 
Error: "m4boot" not defined                                                  
Hit any key to stop autoboot:  0                                                
switch to partitions #0, OK                                                     
mmc0(part 0) is current device                                                  
reading uEnv.txt                                                                
544 bytes read in 23 ms (22.5 KiB/s)                                            
Loaded environment from uEnv.txt                                                
Importing environment from mmc ...                                              
reading zImage                                                                  
9707456 bytes read in 313 ms (29.6 MiB/s)                                       
reading imx7d-pico_pi.dtb                                                       
44582 bytes read in 22 ms (1.9 MiB/s)                                           
reading uramdisk.img                                                            
** Unable to read file uramdisk.img **                                          
boota mmc0                                                                      
boota: bad boot image magic  

Regards,
Amit S

**Comment by wigcheng** [comment]
Do you try this instruction before?
https://github.com/technexion-android/cookers/tree/tn-o8.0.0_1.0.0-ga

**Comment by amsurana** [comment]
Hi,
Yes. I tried that. Please check out the flashing logs. I noticed that the AOSP code doesn't generate `uramdisk.img`. Not sure if it's relevant for Android. 
[imx7_install_logs.txt](https://github.com/technexion-android/manifest/files/3540357/imx7_install_logs.txt)

**Comment by wigcheng** [comment]
Seems you type the flashcard command with wrong place, it must be in the root folder of source code.
Another way, generate the uramdisk.img manually:
sudo mkimage -A arm -O linux -T ramdisk -C none -a 0x83800000 -n "Android Root Filesystem" -d ./out/target/product/pico_7d/ramdisk.img ./out/target/product/pico_7d/uramdisk.img then try again.

Thanks

**Comment by amsurana** [comment]
Great. This instruction helped. I did it manually and things worked as mentioned in the README file.

Is it possible to update the README file with instructions to prepare the IMG file that can be flashed using the installer ftp://ftp.technexion.net/development_resources/development_tools/installer/  

Thank you!

**Comment by wigcheng** [comment]
We will update it on new installer in the future, thanks.

**Comment by veerpawan** [comment]
Hi, I tried to download the **Technexion Android 8 SDK for i.MX6/i.MX7 Platforms**  by using repo tool but not able to download. May I know what is the minimum internet speed to download the source code?

**Comment by wigcheng** [comment]
Could you post your error message here? I think should be missing some repos because google sometimes could change/remove their repo.

**Comment by wigcheng** [comment]
Just tried and it works fine, please check your network on your side, thanks!

**Comment by veerpawan** [comment]
Hi. Successfully download the build using fast internet speed. Could you please provide the way to flash images on TechNexion Board?  Gone through this link **https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.0.1_8m-ga#technexion-android-9-sdk-for-imx8-platforms** but bit confusing about UUU tool.

**Comment by wigcheng** [comment]
So which platform did you use, IMX6/IMX7 or IMX8? They're different flash ways..

**Comment by veerpawan** [comment]
IMX8 PICO MINI... Want to flash Android image.

**Comment by wigcheng** [comment]
Do you download demo image before? it has uuu tool inside the zip file with instruction.
After installed uuu tool, then you can flash image manually or adapt lazy way:
$ uuu_flashcard 7

Must be install uuu tool first.

**Comment by veerpawan** [comment]
Successfully download the UUU tool. can you please let me know where to put UUU tool and then how to flash the image. I am completely newby in TechNexion.

**Then install uuu to different environment:

Refer Q&A item 3 of Chapter 5 on User Manual**


Follow this step but not able to knwo how to install in differenet environement?


This is my directory of output image.


/home/chetu/TechNexionNew/out/target/product/pico_imx8mm

**Comment by TannerDBlack** [comment]
Pawan hopefully this will answer your questions 
https://github.com/TechNexion/u-boot-edm/wiki/Use-mfgtool-%22uuu%22-to-flash-eMMC

**Comment by veerpawan** [comment]
Getting this error


This script is validated with uuu 1.2.91 version, please align with this version.
dtbo is supported
dual slot is supported
generate lines to flash partition-table-13GB.img to the partition of gpt
generate lines to flash u-boot-imx8mm.imx to the partition of bootloader0
generate lines to flash dtbo-imx8mm.img to the partition of dtbo_a
generate lines to flash boot.img to the partition of boot_a
generate lines to flash system.img to the partition of system_a
generate lines to flash vendor.img to the partition of vendor_a
generate lines to flash vbmeta-imx8mm.img to the partition of vbmeta_a
generate lines to flash dtbo-imx8mm.img to the partition of dtbo_b
generate lines to flash boot.img to the partition of boot_b
generate lines to flash system.img to the partition of system_b
generate lines to flash vendor.img to the partition of vendor_b
generate lines to flash vbmeta-imx8mm.img to the partition of vbmeta_b
uuu script generated, start to invoke uuu with the generated uuu script
./uuu_imx_android_flash.sh: line 524: uuu: command not found
root@chetuiwk2066:/home/chetu/TechNexionNew/out/target/product/pico_imx8mm#

**Comment by wigcheng** [comment]
Did you copy your downloaded 'uuu' binary into /usr/bin or /bin? It seems not yet...

**Comment by veerpawan** [comment]
By using the below commands successfully able to flash Android image.
    • $ sudo su
    • chmod +x uuu
    • chmod +x uuu_imx_android_flash.sh
    • sudo ./uuu_imx_android_flash.sh -f imx8mm -e
    • sudo su
    • ./uuu /tmp/uuu.lst



Now trying to setup the WIFI and Bluetooth driver in next step but not able to locate **<source folder>/device/fsl/pico_8m/wifi-firmware/** wifi-firmware folder.

**Comment by tannermlx** [comment]
Pawan, contact sales@technexion.com, they cannot distribute the 9377 drivers with AOSP due to licensing. But they will send them to you.

**Comment by veerpawan** [comment]
I already get the drivers from TechNexion sales Team but not able to find any folder name "wifi-firmware" 
In AOSP current directory I have is sourcefolder/device/fsl/imx8m.


As readme file mentioned----
After getting the firmware binary: .. Decompress the tarball and put all the firmware files into

<source folder>/device/fsl/pico_8m/wifi-firmware/

**Comment by tannermlx** [comment]
You make the folder.

**Comment by veerpawan** [comment]
Make the folder and placed files provided by the TechNexion sales team and then again create build and flash on the board. Still not able to use WIF and Bluetooth.

**Comment by tannermlx** [comment]
Two lines above in the readme:
This SDK is supporting Qualcomm(QCA) WLAN module - QCA9377 as default configuration, Because of the license restriction, please contact TechNexion FAE or Sales to get licensed firmware files, default is disabled.

You need to enable it in the build config for your board. There will be a commented out line in the config.

**Comment by veerpawan** [comment]
Where I can find the config file?

**Comment by wigcheng** [comment]
Could you show me what's your firmware files inside zip?

**Comment by veerpawan** [comment]
These are folders  **qca**, **qca6174**, **qca9377**, **wlan**.

**Comment by wigcheng** [comment]
What's content inside the qca9377 folder?

**Comment by veerpawan** [comment]
bdwlan30.bin   
CadenceLicense.txt
Notice.txt
otp30.bin
qwlan30.bin
utf30.bin

**Comment by veerpawan** [comment]
My current directory is
home/chetu/TechNexionNew/device/fsl/pico_8m/  all folders od WIF **qca**, **qca6174**, **qca9377**, **wlan**.

**Comment by wigcheng** [comment]
$ mkdir -p <source_code>/device/fsl/imx8m/pico_imx8mm/wifi-firmware/QCA9377
$ cp -rv <your_firmware_folder>/qca9377/* <source_code>/device/fsl/imx8m/pico_imx8mm/wifi-firmware/QCA9377/
$ cp -rv <your_firmware_folder>/wlan  <source_code>/device/fsl/imx8m/pico_imx8mm/wifi-firmware/QCA9377/
$ cp -rv <your_firmware_folder>/qca/*  <source_code>/device/fsl/imx8m/pico_imx8mm/bluetooth/

Then re-compile again, should be works.

**Comment by veerpawan** [comment]
Bluetooth is working but WIFI still not working.

Do We Need to uncomment any config file?


Wi-Fi MAC Address
02:00:00:00:00:00

Bluetooth address
a valid number

**Comment by veerpawan** [comment]
Hi,
Could you please let me know the steps to enable WiFi?

**Comment by veerpawan** [comment]
Wi-Fi and Bluetooth working fine on the demo image but not working on the created new build of Android 9.

**Comment by patusaembedded** [comment]
@wigcheng 
 
Hi,

I need build android 8 to my imx7d-pico, becuase I need **RPMsg** in my device (kernel 4.9.x)

**I have issues.**

e.g.: I flashed a ready-made technexion image from android 8 (using balenaEtcher) as well as i had the android things, but i need to prepare the **RPMsg** in the kernel first and then play the image in imx7d-pico
 
 **The commands I'm using and getting an error are as follows:**
  
 mkdir Android6
  cd Android6
  repo init -u https://github.com/technexion-android/manifest -b tn-o8.0.0_1.0.0-ga
  repo sync -j4
  cd cookers
  docker build -t build_droid8 .
  sudo docker run --privileged=true --name mx8_build  -v /home/neuberfran/Android6:/home/mnt -t -i build_droid8 bash
  sud docker ps -a
  sudo docker rm -v mx8_build
  sudo docker run --privileged=true --name mx8_build  -v /home/neuberfran/Android6:/home/mnt -t -i build_droid8 bash
  (this command jumpe me to **part 06**)
  
  But in home/neuberfran/Android6 I continue with this commands:
  sudo docker ps -a
  sudo docker start  mx8_build
  sudo docker exec -it mx8_build bash

  
  **part 06 i**n root, because this command: sudo docker run --privileged=true --name mx8_build  -v /home/neuberfran/Android6:/home/mnt -t -i build_droid8 bash  **this command jumpe me to /  (directory root) of the container**
  
  I don't know why, I go to **/** _in root mode_
  
  _cd /home/mnt_ 
  
  source cookers/env.bash.imx7.pico.pi.lcd
  merge_restricted_extras
  cook -j4
  
  cd /home/mnt/out/target/product/pico_7d
  flashcard /dev/sdd
  
  
  
  **Some of the errors I'm getting are?**
  
  mkimage: Can't open ./out/target/product/pico_7d/ramdisk.img: No such file or directory
== download the system ==
dd: failed to open '/home/mnt/out/target/product/pico_7d/system_raw.img': No such file or directory
== download the vendor ==
dd: failed to open '/home/mnt/out/target/product/pico_7d/vendor_raw.img': No such file or directory
== download the recovery ==
dd: failed to open '/home/mnt/out/target/product/pico_7d/recovery.img': No such file or directory

![Captura de tela de 2021-12-13 00-01-35](https://user-images.githubusercontent.com/71419485/145909259-613f42de-3ffb-411a-b6db-09fd7b96e5e1.png)

**Comment by wigcheng** [comment]
It seems you running flash image command in docker container, container cannot connect with outside physical storage such as eMMC or uSD card ( need additional tweaking).

So please issue flash command on host OS side, should be works, thanks.

**Comment by patusaembedded** [comment]
@wigcheng The command sudo docker run --privileged=true --name mx8_build  -v /home/neuberfran/Android6:/home/mnt -t -i build_droid8 bash **is correct?** What is its function within this sequence of commands? Is it necessary?
(from what you said in the answer above, such a command is not necessary as it is automatically throwing me to the root user and / (root) folder of the container.

**Comment by wigcheng** [comment]
Yes, if you choose docker container way, the stages as follows:
Compile stage is in docker container.
Flash image stage is back to in host PC side.

Sorry the instruction is not clearly ( default is assume the customers compile and flash image both on the host PC side)

**Comment by patusaembedded** [comment]
@wigcheng I don't have flashcard (or sudo flashcard) command in nowhere from the Android6 folder (which is where I threw the project)

![Captura de tela de 2021-12-13 23-23-37](https://user-images.githubusercontent.com/71419485/145921699-5423305d-7e28-4d46-a327-c62444e01983.png)

**Comment by wigcheng** [comment]
??? I thought your target OS is Android 8 as your above mention, isn't it?
Android 6 does not support anymore here, thanks.

**Comment by patusaembedded** [comment]
@wigcheng Yes. it is android 8. Only the folder name is Android6

**Comment by patusaembedded** [comment]
@wigcheng Pls. tell me Where I will find flashcard command?

**Comment by wigcheng** [comment]
No flashcard?, it's impossible, did you source the cookers on host PC side first?
$ cd (source folder)
$ source cookers/env.bash.imx7d.pico-imx7.pi.lcd-5-inch
$ flashcard /dev/sdx 3
sdx means your device node of eMMC mounted storage, 3 means the image size what you want (3GB).

It will auto search out folder and copy the relate match images to your eMMC.
That's it.

**Comment by patusaembedded** [comment]
@wigcheng Sorry I forgot source cookers/env.bash.imx7.pico.pi.lcd. Because I restart PC after lunch. Now I have flashcard. Please, What about merge_restricted_extras command? What  it's  function?

What's difference between cook and heat ?

**Comment by patusaembedded** [comment]
@wigcheng No ftp is working here:

ftp://ftp.technexion.net/demo_software/

ftp://ftp.technexion.net/demo_software/PICO/IMX7/pico-imx7-emmc/Installer/pico-imx7_pico-nymph_ubuntu-16.04_installer_vga-640x480_20180313.zip

ftp://ftp.technexion.net/development_resources/development_tools/installer/

**Comment by wigcheng** [comment]
> 

cook -> build all source code with rewrite defconfig
throw && cook -> clean build
heat -> re-build build all source code
merge_restricted_extras -> install NXP extra libraries


New download link:
https://download.technexion.com/

**Comment by patusaembedded** [comment]
@wigcheng 
**I've done several compilations and the files never appear:**

ramdisk.img,system_raw.img,vendor_raw.img, recovery.img. etc..

```
- neuberfran@ubuntu2010:~/Android6/out/target/product/pico_7d$ ls
- android-info.txt       fake_packages     partition-table-14GB.bpt  partition-table-7GB.bpt  previous_build_config.mk  system
- build_fingerprint.txt  gen               partition-table-14GB.img  partition-table-7GB.img  recovery                  vendor
- clean_steps.mk         module-info.json  partition-table-28GB.bpt  partition-table.bpt      root
- data                   obj               partition-table-28GB.img  partition-table.img      symbols
```

**Comment by patusaembedded** [comment]
@wigcheng

Why  I can't see this files : ramdisk.img,system_raw.img,vendor_raw.img, recovery.img. etc.. after build
?

**Comment by patusaembedded** [comment]
@wigcheng

**I've done several compilations and the files never appear:**

![Captura de tela de 2022-01-05 11-06-24](https://user-images.githubusercontent.com/71419485/148230610-b90c43b4-47d1-42d3-a775-967092b0680d.png)

**Comment by neuberfran** [comment]
@amsurana @wigcheng 
Issue with this without docker:

**steps:** 

1) mkdir Android7
2) repo init -u https://github.com/technexion-android/manifest -b tn-o8.0.0_1.0.0-ga
3) repo sync -j8
4) docker build -t build_droid8 .
5) source cookers/env.bash.imx7.pico.pi.lcd
6) merge_restricted_extras
7) cook -j8


![Captura de tela de 2022-01-06 19-20-34](https://user-images.githubusercontent.com/38701397/148460870-aa429400-4053-4850-ac3b-84da4bfd30fb.png)

**Comment by patusaembedded** [comment]
Not Solved yet
![Captura de tela de 2022-01-07 18-57-49](https://user-images.githubusercontent.com/71419485/148615926-b372079b-3f49-42b6-87e0-8c2ecf32d0e4.png)

**Comment by patusaembedded** [comment]
@wigcheng I need to do changes in kernel. But I have issues:
steps:
1) make menuconfig in home/user/ndroid_build/vendor/nxp-opensource/kernel_imx
1.1) include RPMsg 
2) heat -j8 in home/user/ndroid_build
![issue7](https://user-images.githubusercontent.com/71419485/148689675-0179b6b1-be56-4908-a489-0d217c15876e.png)

**Comment by wigcheng** [comment]
..........

I suggest you can study what's difference between Linux Kernel environment and Android Kernel environment, I cannot answer you for these kind of rookie questions one by one, sorry, hope you understand. This place is for technical issue report, not a school.

I can give you a way:
In Android, all kernel output files include config file are in the path as follows:
( source )/out/target/product/pico_imx7d/obj/KERNEL_OBJ/, you should compile manually there.

Thanks

**Comment by patusaembedded** [comment]
@wigcheng If this place were a school you would never be chosen the my teacher
cheers

**Comment by patusaembedded** [comment]
@wigcheng I stay trying include imx_rpmsg_tty (module/driver) in my AOSP 8 project using this site (https://android.serverbox.ch/?p=1738&cpage=1#comment-329470)  just as a command reference (except: repo init, repo sync ,merge_restricted_extras and flashcard.

I got compilation success, but in pico_7d the **modules** folder in /lib **doesn't appear**. Only the firmware folder. **What is missing in my commands?** Regarding the photo below (heat command and modules_install), how to include this in the link mentioned above in this post?
![Captura de tela de 2022-01-11 23-45-09](https://user-images.githubusercontent.com/71419485/149054712-f25d6223-1b83-44a9-84e1-101dcec77cfe.png)

**Comment by wigcheng** [comment]
Refer Android 9 BoardConfig makefile setting for kernel module
https://github.com/technexion-android/platform_device_fsl/blob/tn-p9.0.0_2.2.0-ga/imx7d/pico_imx7/BoardConfig.mk#L45

In Android , all kernel modules need assign manually in Makefile.

Don't refer Android 8's Makefile, it's dirty way, of course not made by me :)

**Comment by patusaembedded** [comment]
@wigcheng Can you directly enable imx_rpmsg_tty, imx_rpmsg_pingpong and virtio modules directly in technexion Android 9 original (in github) or not?
(To make my job easier)

**Comment by patusaembedded** [comment]
@wigcheng I have issue to sync with repo sync -j8 and/ or repo sync -j4 in **repo init -u https://github.com/technexion-android/manifest -b tn-p9.0.0_2.2.0-ga_tn2.0**


$ repo init -u https://github.com/technexion-android/manifest -b tn-p9.0.0_2.2.0-ga_tn2.0
$ repo sync -j<N> (N is up to cores numbers on your host PC)


$ repo init -u https://github.com/technexion-android/manifest -b tn-p9.0.0_2.2.0-ga
$ repo sync -j<N> (N is up to cores numbers on your host PC)

**repo --version**
**repo version v2.19**
       (from https://gerrit.googlesource.com/git-repo)
       (tracking refs/heads/stable)
       (Wed, 1 Dec 2021 15:27:16 +0000)
**repo launcher version 2.17**
       (from /home/neuberfran/bin/repo)
       (currently at 2.19)
repo User-Agent git-repo/2.19 (Linux) git/2.25.1 Python/3.8.10
git 2.25.1
git User-Agent git/2.25.1 (Linux) git-repo/2.19
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
OS Linux 5.8.0-63-generic (#71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021)
CPU x86_64 (x86_64)
Bug reports: https://bugs.chromium.org/p/gerrit/issues/entry?template=Repo+tool+issue

![Captura de tela de 2022-01-12 10-07-05](https://user-images.githubusercontent.com/71419485/149146342-53c9b1f9-dd0f-4e10-8143-a45b9c6c3676.png)

**Comment by patusaembedded** [comment]
@wigcheng 
Hi,
Could you please
talk about my posts above
?

**Comment by wigcheng** [comment]
Just tested, I have no this issue here, please check your network environment.
In addition, please open a new ticket, don't borrow other contributor, thanks.

Updating files: 100% (569/569), done.
Updating files: 100% (243/243), done.
Updating files: 100% (201/201), done.
Updating files: 100% (1066/1066), done.
Updating files: 100% (356/356), done.
Updating files: 100% (2219/2219), done.
Updating files: 100% (132/132), done.
Updating files: 100% (1112/1112), done.
Updating files: 100% (429/429), done.
Updating files: 100% (516/516), done.
Updating files: 100% (2871/2871), done.
Updating files: 100% (6246/6246), done.
Updating files: 100% (239/239), done.
Updating files: 100% (1157/1157), done.
Updating files: 100% (736/736), done.
Updating files: 100% (559/559), done.
Updating files: 100% (995/995), done.
Updating files: 100% (2841/2841), done.
Updating files: 100% (369/369), done.
Updating files: 100% (50/50), done.
Updating files: 100% (7584/7584), done.
Updating files: 100% (305/305), done.
Updating files: 100% (81/81), done.
Updating files: 100% (954/954), done.
Updating files: 100% (9937/9937), done.
Updating files: 100% (201/201), done.
Updating files: 100% (18572/18572), done.
Updating files: 100% (124/124), done.
Updating files: 100% (127/127), done.
Updating files: 100% (810/810), done.
Updating files: 100% (449/449), done.
Updating files: 100% (89/89), done.
Updating files: 100% (1546/1546), done.
Updating files: 100% (7866/7866), done.
Updating files: 100% (3968/3968), done.
Updating files: 100% (149/149), done.
Updating files: 100% (2439/2439), done.
Updating files: 100% (7584/7584), done.
Updating files: 100% (664/664), done.
Updating files: 100% (176/176), done.
Updating files: 100% (44/44), done.
Updating files: 100% (111/111), done.
Updating files: 100% (66/66), done.
Updating files: 100% (202/202), done.
Updating files: 100% (4410/4410), done.
Updating files: 100% (229/229), done.
Updating files: 100% (107/107), done.
Updating files: 100% (502/502), done.
Updating files: 100% (259/259), done.
Updating files: 100% (757/757), done.
Updating files: 100% (85/85), done.
Updating files: 100% (189/189), done.
Updating files: 100% (217/217), done.
Updating files: 100% (3754/3754), done.
Updating files: 100% (97/97), done.
Updating files: 100% (771/771), done.
Updating files: 100% (1744/1744), done.
Updating files: 100% (1303/1303), done.t/vts-testcase/securityUpdating files:  81% (5072/6259)
Updating files: 100% (181/181), done.
Updating files: 100% (1765/1765), done.
Updating files: 100% (266/266), done.
Updating files: 100% (821/821), done.
Updating files: 100% (378/378), done.
Updating files: 100% (1016/1016), done.
Updating files: 100% (6259/6259), done.
Updating files: 100% (4494/4494), done.
Updating files: 100% (216/216), done.
Updating files: 100% (25/25), done.
Updating files: 100% (454/454), done.
Updating files: 100% (63464/63464), done.
Updating files: 100% (66/66), done.
Updating files: 100% (64/64), done.
Updating files: 100% (50/50), done.
Updating files: 100% (184/184), done.xternal/rapporUpdating files:  48% (203/421)
Updating files: 100% (1641/1641), done.
Updating files: 100% (284/284), done.
Updating files: 100% (1031/1031), done.
Updating files: 100% (421/421), done.
Updating files: 100% (33748/33748), done.
Updating files: 100% (507/507), done.
Updating files: 100% (383/383), done.
Updating files: 100% (53/53), done.
Updating files: 100% (8/8), done.
Updating files: 100% (56/56), done.
Updating files: 100% (809/809), done.
Updating files: 100% (21720/21720), done.
Updating files: 100% (934/934), done.
Updating files: 100% (683/683), done.
Updating files: 100% (348/348), done.
Updating files: 100% (441/441), done.
Updating files: 100% (149/149), done.
Updating files: 100% (178/178), done.
Updating files: 100% (1330/1330), done.
Updating files: 100% (323/323), done.
Updating files: 100% (825/825), done.
Updating files: 100% (14318/14318), done.
Updating files: 100% (488/488), done.
Updating files: 100% (6/6), done.rmwareUpdating files:   4% (368/9195)
Updating files: 100% (8235/8235), done.
Updating files: 100% (442/442), done.
Updating files: 100% (280/280), done.
Updating files: 100% (3223/3223), done.
Updating files: 100% (1514/1514), done.
Updating files: 100% (1019/1019), done.
Updating files: 100% (1976/1976), done.
Updating files: 100% (1325/1325), done.
Updating files: 100% (1469/1469), done.
Updating files: 100% (1761/1761), done.
Updating files: 100% (8/8), done.
Updating files: 100% (424/424), done.
Updating files: 100% (209/209), done.
Updating files: 100% (57/57), done.
Updating files: 100% (1614/1614), done.
Updating files: 100% (8/8), done.
Updating files: 100% (424/424), done.
Updating files: 100% (245/245), done.
Updating files: 100% (618/618), done.
Updating files: 100% (490/490), done.
Updating files: 100% (2041/2041), done.
Updating files: 100% (328/328), done.
Updating files: 100% (1000/1000), done.
Updating files: 100% (695/695), done.
Updating files: 100% (1158/1158), done.
Updating files: 100% (390/390), done.
Updating files: 100% (652/652), done.
Updating files: 100% (269/269), done.
Updating files: 100% (50/50), done.
Updating files: 100% (323/323), done.
Updating files: 100% (679/679), done.
Updating files: 100% (131/131), done.
Updating files: 100% (164/164), done.
Updating files: 100% (5502/5502), done.
Updating files: 100% (2818/2818), done.
Updating files: 100% (1461/1461), done.
Updating files: 100% (4584/4584), done.
Updating files: 100% (3741/3741), done.
Updating files: 100% (758/758), done.
Updating files: 100% (859/859), done.
Updating files: 100% (101/101), done.
Updating files: 100% (118/118), done.
Updating files: 100% (1035/1035), done.
Updating files: 100% (158/158), done.
Updating files: 100% (5766/5766), done.ternal/libcupsUpdating files:  24% (1384/5766)
Updating files: 100% (9195/9195), done.
Updating files: 100% (401/401), done.
Updating files: 100% (4954/4954), done.
Updating files: 100% (90/90), done.
Updating files: 100% (677/677), done.
Updating files: 100% (828/828), done.
Updating files: 100% (851/851), done.
Updating files: 100% (1057/1057), done.
Updating files: 100% (763/763), done.
Updating files: 100% (12382/12382), done.rnal/flacUpdating files:  35% (5515/15547)
Updating files: 100% (417/417), done.external/libusb-compatUpdating files:  78% (23432/30040)
Updating files: 100% (30040/30040), done.
Updating files: 100% (2842/2842), done.
Updating files: 100% (1582/1582), done.
Updating files: 100% (102/102), done.
Updating files: 100% (74/74), done.
Updating files: 100% (15547/15547), done.
Updating files: 100% (856/856), done.
Updating files: 100% (291/291), done.
Updating files: 100% (3226/3226), done.
Updating files: 100% (9487/9487), done.
Updating files: 100% (214/214), done.external/ipsec-toolsUpdating files:  91% (739/812)
Updating files: 100% (17/17), done.
Updating files: 100% (812/812), done.
Updating files: 100% (760/760), done.
Updating files: 100% (576/576), done.
Updating files: 100% (4534/4534), done.
Updating files: 100% (121/121), done.
Updating files: 100% (228/228), done.
Updating files: 100% (81/81), done.m/hardware/qcom/sdm845/vrUpdating files:  68% (11/16)
Updating files: 100% (137/137), done.
Updating files: 100% (16/16), done.
Updating files: 100% (12/12), done.
Updating files: 100% (1478/1478), done.
Updating files: 100% (110/110), done.
Updating files: 100% (173/173), done.
Updating files: 100% (12188/12188), done.
Updating files: 100% (2500/2500), done.
Updating files: 100% (4195/4195), done.
Updating files: 100% (17/17), done.
Updating files: 100% (413/413), done.
Updating files: 100% (4112/4112), done.
Updating files: 100% (27/27), done.
Updating files: 100% (36/36), done.
Updating files: 100% (144/144), done.
Updating files: 100% (88/88), done.
Updating files: 100% (1597/1597), done.ternal/python/enum34Updating files:  29% (150/514)
Updating files: 100% (514/514), done.
Updating files: 100% (524/524), done.external/adhdUpdating files:  17% (392/2218)
Updating files: 100% (1055/1055), done.ternal/wycheproofUpdating files:  22% (488/2218)
Updating files: 100% (1775/1775), done.ckages/services/BuiltInPrintServiceUpdating files:  21% (3179/15073)
Updating files: 100% (821/821), done.
Updating files: 100% (292/292), done.
Updating files: 100% (633/633), done.external/nevenUpdating files:  43% (6553/15073)
Updating files: 100% (8137/8137), done.
Updating files: 100% (715/715), done.
Updating files: 100% (257/257), done.
Updating files: 100% (5661/5661), done.
Updating files: 100% (17/17), done.
Updating files: 100% (1160/1160), done.
Updating files: 100% (1150/1150), done.
Updating files: 100% (571/571), done.
Updating files: 100% (41/41), done.
Updating files: 100% (307/307), done.
Updating files: 100% (1000/1000), done.
Updating files: 100% (241/241), done.
Updating files: 100% (97/97), done.
Updating files: 100% (115/115), done.
Updating files: 100% (26/26), done.
Updating files: 100% (2218/2218), done.
Updating files: 100% (297/297), done.
Updating files: 100% (5054/5054), done.
Updating files: 100% (816/816), done.
Updating files: 100% (127/127), done.
Updating files: 100% (178/178), done.
Updating files: 100% (338/338), done.
Updating files: 100% (870/870), done.frameworks/opt/net/lowpanUpdating files:  94% (818/870)
Updating files: 100% (335/335), done.
Updating files: 100% (378/378), done.
Updating files: 100% (1792/1792), done.
Updating files: 100% (516/516), done.hardware_interfacesUpdating files:  74% (384/516)
Updating files: 100% (516/516), done.
Updating files: 100% (558/558), done.
Updating files: 100% (1651/1651), done.
Updating files: 100% (499/499), done.
Updating files: 100% (858/858), done.
Updating files: 100% (672/672), done.
Updating files: 100% (9936/9936), done.ckages/apps/DevCameraUpdating files:  90% (9040/9936)
Updating files: 100% (7/7), done.
Updating files: 100% (2949/2949), done.
Updating files: 100% (4283/4283), done.ternal/tagsoupUpdating files:  72% (10853/15073)
Updating files: 100% (12663/12663), done.
Updating files: 100% (123/123), done.
Updating files: 100% (2248/2248), done.ckages/apps/StkUpdating files:  50% (8077/16011)
Updating files: 100% (381/381), done.
Updating files: 100% (16011/16011), done.rnal/conscryptUpdating files:  65% (10419/16011)
Updating files: 100% (1917/1917), done.
Updating files: 100% (8081/8081), done.
Updating files: 100% (4867/4867), done.
Updating files: 100% (8073/8073), done.
Updating files: 100% (3210/3210), done.
Updating files: 100% (15073/15073), done.
Updating files: 100% (74/74), done.
Updating files: 100% (6745/6745), done.
Updating files: 100% (16/16), done.
Updating files: 100% (9168/9168), done.
Updating files: 100% (1524/1524), done.
Updating files: 100% (4089/4089), done.
Updating files: 100% (16166/16166), done.c/qemuUpdating files:  32% (5317/16166)
Updating files: 100% (37037/37037), done.
Updating files: 100% (197/197), done.
Updating files: 100% (266/266), done.
Updating files: 100% (190/190), done.
Updating files: 100% (10158/10158), done.
Updating files: 100% (113/113), done.
Updating files: 100% (220/220), done.
Updating files: 100% (257/257), done.
Updating files: 100% (1150/1150), done.
Updating files: 100% (268/268), done.
Updating files: 100% (192/192), done.
Updating files: 100% (1706/1706), done.
Updating files: 100% (3541/3541), done.
Updating files: 100% (892/892), done.
Updating files: 100% (4427/4427), done.stem/keymasterUpdating files:  97% (4317/4427)
Updating files: 100% (222/222), done.
Updating files: 100% (259/259), done.
Updating files: 100% (1944/1944), done.
Updating files: 100% (1765/1765), done.
Checking out: 100% (699/699), done in 12m2.357s
repo sync has finished successfully.
